"""form

Revision ID: 442fdca2d3d8
Revises:
Create Date: 2026-04-01 01:20:10.484381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "442fdca2d3d8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("surnameUser", sa.String(length=50), nullable=False),
        sa.Column("nameUser", sa.String(length=50), nullable=False),
        sa.Column("isChangedSurnameBefore", sa.Boolean(), nullable=True),
        sa.Column("patronymicUser", sa.String(length=50), nullable=False),
        sa.Column("latinSurname", sa.String(length=50), nullable=False),
        sa.Column("latinName", sa.String(length=50), nullable=False),
        sa.Column("dayBirthday", sa.Integer(), nullable=False),
        sa.Column("monthBirthday", sa.String(length=50), nullable=False),
        sa.Column("yearBirthday", sa.Integer(), nullable=False),
        sa.Column("maritalStatus", sa.String(length=50), nullable=False),
        sa.Column("education", sa.String(length=50), nullable=False),
        sa.Column("phoneNumber", sa.String(length=15), nullable=False),
        sa.Column("email", sa.String(length=70), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forms")
    # ### end Alembic commands ###
